name: Pipeline Principal CI/CD

on:
  push:
    branches: [ main ]

jobs:
  # 1. Tarea de Construcción
  construir:
    runs-on: self-hosted
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      # --- CACHE DE COMPOSER ---
      - name: Directorio de Cache de Composer
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache de dependencias PHP
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      # --- CACHE DE NPM ---
      - name: Cache de dependencias Node
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      # --- INSTALACIÓN Y BUILD ---
      - name: Build Artifact (PHP & JS)
        run: |
          # Instalamos dependencias respetando el lock
          composer install --no-dev --optimize-autoloader --no-interaction
          npm ci
          npm run build
          
          # Pausa para sincronización de archivos y compresión
          sleep 2
          tar -czf release.tar.gz . --ignore-failed-read
          
      - name: Guardar Artefacto
        uses: actions/upload-artifact@v4
        with:
          name: app-package
          path: release.tar.gz

  # 2. Despliegue a Staging (Llamada al Archivo 2)
  deploy_staging:
    needs: construir
    uses: ./.github/workflows/staging.yml
    secrets: inherit

  # 3. Despliegue a Producción (Llamada al Archivo 3)
  deploy_production:
    needs: deploy_staging
    uses: ./.github/workflows/production.yml
    secrets: inherit